[package]
name = "vortex-metrics"
authors = { workspace = true }
categories = { workspace = true }
description = "Vortex Metrics"
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
dashmap = { workspace = true }
serde_json = { workspace = true }
parking_lot = { workspace = true }
sketches-ddsketch = { workspace = true }
vortex-session = { workspace = true }

[lints]
workspace = true
